### ISSUE TITLE
Configure for CI, include sample project for development

### ISSUE THREAD

**Issue by dleehr** [Duke-GCB/gcb-web-auth#3]
Some other django auth apps for reference, by no means exhaustive

- https://github.com/Duke-GCB/django-iplant-auth
- https://github.com/Duke-GCB/django-shibboleth-adapter

**Comment by johnbradley** [comment]
I don't see how the CI for https://github.com/Duke-GCB/django-iplant-auth works. I think the demo directory is just for documentation purposes.

**Comment by johnbradley** [comment]
Fixed by #7 and #11
